x-uffizzi:
  ingress:
    service: app
    port: 8080

services:
  app:
    build: .
    environment:
      NODE_ENV: staging
      DATABASE_URL: postgres://dbamdi_user:JCS4K9c8XtvV21vOCJ6VOhDGuDdw6A75@dpg-cfn308ta499f2891cji0-a.frankfurt-postgres.render.com/dbamdi
      TZ: Asia/Colombo
      LANGUAGE: EN
    deploy:
      resources:
        limits:
          memory: 4000M
    restart: always
    ports:
      - "3000:3000"
    privileged: true
    depends_on:
      - app
    cap_add:
      - SYS_ADMIN
    restart: always
volumes:
  data:
