x-uffizzi:
  ingress:
    service: app
    port: 8080

services:
  app:
    build: .
    environment:
      NODE_ENV: staging
      DATABASE_URL: postgres://amdibase_user:jULpW1IVgpxL0FpmE44oFT1iGYpWQtj5@dpg-cf97iu9mbjss4meeq6gg-a.frankfurt-postgres.render.com/amdibase
    deploy:
      resources:
        limits:
          memory: 4000M
    restart: always
    ports:
      - "3000:3000"
    privileged: true
    depends_on:
      - app
    cap_add:
      - SYS_ADMIN
    restart: always
volumes:
  data:
